#!/usr/bin/env fish

echo ""
dots log --name-status HEAD^..HEAD

set_color -d red
echo "-----------------------------------------------------------------------"
set_color normal

dots status

set_color -d red
echo "-----------------------------------------------------------------------"
set_color normal
