#!/usr/bin/env fish

vscodex silent-backup
dots add .config/Code/User/vscodex
dots add .config/Code/User/snippets/.
dots add .config/Code/User/keybindings.json
dots add .config/Code/User/settings.json

dots add .local/share/fish/fish_history
dots add .local/share/z/data
